sudo: false
language: python
# command to install dependencies
install:
    - make init
# command to run tests
script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-metadata; fi
  - make ci
cache: pip
jobs:
  include:
    - stage: check
      script:
        - make check
      python: 
        - '3.6'
    - stage: test
      script:
        - make test-metadata
        - make ci
      python: 
        - '3.6'
        - '3.7'
        - '3.7-dev'
    - stage: coverage
      python: '3.6'
      script:
        - make coverage
        - codecov